Special case versions lower than '0.11*' to not pass new --data-dir

diff --git a/scripts/cloudron-setup b/scripts/cloudron-setup
--- a/scripts/cloudron-setup
+++ b/scripts/cloudron-setup
@@ -244,9 +244,17 @@ fi
 
 echo "=> Installing version ${version} (this takes some time) ..."
 echo "${data}" > "${DATA_FILE}"
-if ! /bin/bash "${box_src_tmp_dir}/scripts/installer.sh" --data-file "${DATA_FILE}" --data-dir "${baseDataDir}" &>> "${LOG_FILE}"; then
-    echo "Failed to install cloudron. See ${LOG_FILE} for details"
-    exit 1
+# poor mans semver
+if [[ ${version} == "0.11"* ]]; then
+    if ! /bin/bash "${box_src_tmp_dir}/scripts/installer.sh" --data-file "${DATA_FILE}" --data-dir "${baseDataDir}" &>> "${LOG_FILE}"; then
+        echo "Failed to install cloudron. See ${LOG_FILE} for details"
+        exit 1
+    fi
+else
+    if ! /bin/bash "${box_src_tmp_dir}/scripts/installer.sh" --data-file "${DATA_FILE}" &>> "${LOG_FILE}"; then
+        echo "Failed to install cloudron. See ${LOG_FILE} for details"
+        exit 1
+    fi
 fi
 rm "${DATA_FILE}"
 
