Add --dns-provider argument
Maybe someday we can set other providers like route53 etc here

diff --git a/scripts/cloudron-setup b/scripts/cloudron-setup
--- a/scripts/cloudron-setup
+++ b/scripts/cloudron-setup
@@ -17,6 +17,7 @@ domain=""
 provider=""
 encryptionKey=""
 restoreUrl=""
+dnsProvider="manual"
 tlsProvider="le-prod"
 versionsUrl="https://s3.amazonaws.com/prod-cloudron-releases/versions.json"
 version="latest"
@@ -33,6 +34,7 @@ while true; do
     --encryption-key) encryptionKey="$2"; shift 2;;
     --restore-url) restoreUrl="$2"; shift 2;;
     --tls-provider) tlsProvider="$2"; shift 2;;
+    --dns-provider) dnsProvider="$2"; shift 2;;
     --version) version="$2"; shift 2;;
     --versions-url) versionsUrl="$2"; shift 2;;
     --api-server) apiServer="$2"; shift 2;;
@@ -61,6 +63,14 @@ fi
 
 if [[ -z "${encryptionKey}" ]]; then
     echo "--encryption-key for backup encryption is required"
+    exit 1
+fi
+
+if [[ -z "${dnsProvider}" ]]; then
+    echo "--dns-provider is required (noop, manual)"
+    exit 1
+elif [[ "${dnsProvider}" != "noop" && "${dnsProvider}" != "manual" ]]; then
+    echo "--dns-provider must be one of : manual, noop"
     exit 1
 fi
 
@@ -121,6 +131,9 @@ if [[ -z "${restoreUrl}" ]]; then
     "apiServerOrigin": "${apiServer}",
     "tlsConfig": {
         "provider": "${tlsProvider}"
+    },
+    "dnsConfig": {
+        "provider": "${dnsProvider}"
     },
     "backupConfig" : {
         "provider": "filesystem",
