cloudron-activate: always login since activate return token and not accessToken

diff --git a/scripts/cloudron-activate b/scripts/cloudron-activate
--- a/scripts/cloudron-activate
+++ b/scripts/cloudron-activate
@@ -87,11 +87,13 @@ if [[ $(get_status "activated") == "false" ]]; then
 
     wait_for_status "activated" "true"
 else
-    echo "=> Skipping activation. Getting token"
-     if ! activationResult=$($curl -X POST -H "Content-Type: application/json" -d "${activationData}" http://localhost:3000/api/v1/developer/login); then
-        echo "Failed to login with ${activationData}: ${activationResult}"
-        exit 1
-    fi
+    echo "=> Skipping Activation"
+fi
+
+echo "=> Getting token"
+if ! activationResult=$($curl -X POST -H "Content-Type: application/json" -d "${activationData}" http://localhost:3000/api/v1/developer/login); then
+    echo "Failed to login with ${activationData}: ${activationResult}"
+    exit 1
 fi
 
 accessToken=$(echo "${activationResult}" | python3 -c 'import sys, json; print(json.load(sys.stdin)[sys.argv[1]])' "accessToken")
@@ -103,4 +105,6 @@ if ! appstoreResult=$($curl -X POST -H "Content-Type: application/json" -d "${ap
     echo "Failed to setup Appstore account with ${appstoreData}: ${appstoreResult}"
     exit 1
 fi
+
+echo "=> Done!"
 
