Remove now unused dependency dnsutils

diff --git a/scripts/cloudron-setup b/scripts/cloudron-setup
--- a/scripts/cloudron-setup
+++ b/scripts/cloudron-setup
@@ -137,8 +137,8 @@ if [[ "${initBaseImage}" == "true" ]]; then
     fi
 
     echo "=> Installing setup dependencies ..."
-    if ! apt-get install curl dnsutils -y &>> "${LOG_FILE}"; then
-        echo "Could not install setup dependencies (curl and dnsutils)"
+    if ! apt-get install curl -y &>> "${LOG_FILE}"; then
+        echo "Could not install setup dependencies (curl)"
         exit 1
     fi
 
