Move version out of config.js
We now store this in a file called VERSION inside the tarball
itself.

diff --git a/scripts/createReleaseTarball b/scripts/createReleaseTarball
--- a/scripts/createReleaseTarball
+++ b/scripts/createReleaseTarball
@@ -7,20 +7,27 @@ set -eu
 [[ $(uname -s) == "Darwin" ]] && GNU_GETOPT="/usr/local/opt/gnu-getopt/bin/getopt" || GNU_GETOPT="getopt"
 readonly GNU_GETOPT
 
-args=$(${GNU_GETOPT} -o "" -l "output:" -n "$0" -- "$@")
+args=$(${GNU_GETOPT} -o "" -l "output:,version:" -n "$0" -- "$@")
 eval set -- "${args}"
 
 readonly SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
 
 bundle_file=""
+version=""
 
 while true; do
     case "$1" in
     --output) bundle_file="$2"; shift 2;;
+    --version) version="$2"; shift 2;;
     --) break;;
     *) echo "Unknown option $1"; exit 1;;
     esac
 done
+
+if [[ -z "${version}" ]]; then
+    echo "--version is required"
+    exit 1
+fi
 
 readonly TMPDIR=${TMPDIR:-/tmp} # why is this not set on mint?
 
@@ -50,6 +57,7 @@ echo "==> Checking out code box version [${box_version}] and dashboard version [
 (cd "${SOURCE_DIR}" && git archive --format=tar ${box_version} | (cd "${bundle_dir}" && tar xf -))
 (cd "${SOURCE_DIR}/../dashboard" && git archive --format=tar ${dashboard_version} | (mkdir -p "${bundle_dir}/dashboard.build" && cd "${bundle_dir}/dashboard.build" && tar xf -))
 (cp "${SOURCE_DIR}/../dashboard/LICENSE" "${bundle_dir}")
+echo "${version}" > "${bundle_dir}/VERSION"
 
 echo "==> Installing modules for dashboard asset generation"
 (cd "${bundle_dir}/dashboard.build" && npm install --production)
